### ISSUE TITLE
Improper TX power reading

### ISSUE THREAD

**Issue by ok1rp** [afarhan/sbitx#31]
During transmitting the power readings on external W-meter is 38W (Drive set to 100) but on the V2 display TX power is flickering between values 0 and 7W during CW keying at 26wpm speed. (only these two values appear close to TX power bar graph) When keyed down the TX with pump key the value settled at 7W out. (even although the ext. W-meter reads correct almost 40W)

**Comment by afarhan** [comment]
The reading on our power meter is average of on and off and not the peak as
noted in other meters.
If you switch to straight key and transmit you will see the full power
being reported.
- f

**Comment by ok1rp** [comment]
Unfortunately not Farhan. As I reported in the note on the group when I used straight key and transmit, I see 7W settled value while 40W reads the nearby external power meter.
- P

**Comment by afarhan** [comment]
Oh, let me check this at end too.

**Comment by m0prf** [comment]
ok done some updates now real time clock no longer updates just the seconds tick
says 2000/01/01 can this be sorted via ./update please
also power meter says 116 watts when keyed up.

tnx jeffrey

**Comment by m0prf** [comment]
i for got its the ds3231 modual that does not update and seems to be stuck on 2000/01/01

jeffrey   m0prf

**Comment by afarhan** [comment]
It needs you to install some software. Can you follow the instructions on sbitx.net and check? The issue has been fixed

**Comment by m0prf** [comment]
ah just found sbitx and fixt meter and tx settings now for the clock
can you let me know the new board and who and where you sent it .. tnx
jeffrey

**Comment by m0prf** [comment]
ok LOG BOOK still does not save anything and the CW is still all over the place any way i can deal with thses remaining 2 issues

tnx jeffrey

**Comment by afarhan** [comment]
Jeffery,
Type sqlite3 in the command line to check if sqlite3 is installed. If it is
not, you should install it.
Do this :

sudo apt update
sudo apt install sqlite3
sudo apt install libsqlite3-dev

After this, the logbook should work. What keying are you using for cw?
- f

**Comment by m0prf** [comment]
ok i am using a paddle key
works upto 9 words a minuit then it all lags and gets out of sync

jeffrey

**Comment by ok1rp** [comment]
The same here.
CW is unusable with iambic paddle (tried different types)


73 - Petr, OK1RP
--
B: http://goo.gl/Fd2JhJ
YT: https://urlzs.com/UHNH9
MeWe: https://bit.ly/2HGPoDx
MeWe: https://bit.ly/2FmwvDt
--
機能するものを変更しないでください。
What could be easier..?  ¯‍∖‍_‍(‍ツ‍)‍_‍/‍¯

**Comment by afarhan** [comment]
Have you tried with the latest release (may 9th)?

**Comment by m0prf** [comment]
ok i using a paddle key i can do 11 wpm then after that it all gets errors and out of sync maybe an electronic touch paddle would work better who knows .. jeff

**Comment by ok1rp** [comment]
I can test it with several iambic paddle until 50wpm speed if needed. 
At first I am waiting for latest build (May 10th I guess) available as .iso full image for burning SD card. I do not want to make particular updates without safe step back option. 

Petr

73 - Petr, OK1RP
--
B: http://goo.gl/Fd2JhJ
YT: https://urlzs.com/UHNH9
MeWe: https://bit.ly/2HGPoDx
MeWe: https://bit.ly/2FmwvDt
--
機能するものを変更しないでください。
What could be easier..?  ¯‍∖‍_‍(‍ツ‍)‍_‍/‍¯

**Comment by m0prf** [comment]
i tried again still log book will not save came up with something about error 372 and some other junk i did not understand i have a fix for the cw mode solder 2 times 0.0uf caps one on left paddle and one on right then ground the other ends helped a great deal but still no f@@king log book just blank grrrr  ..jeff..

**Comment by ok1rp** [comment]
Jeff,

Can you send some drawing please?
0.0uF? Typo error? :)

I have same problem with logbook. 

73 - Petr, OK1RP
--
B: http://goo.gl/Fd2JhJ
YT: https://urlzs.com/UHNH9
MeWe: https://bit.ly/2HGPoDx
MeWe: https://bit.ly/2FmwvDt
--
機能するものを変更しないでください。
What could be easier..?  ¯‍∖‍_‍(‍ツ‍)‍_‍/‍¯

**Comment by m0prf** [comment]
sorry 0.01 i do not know how to do pictures is is all new to me , if you have 3 wires on your key put 1 cap on left and then 1 cap on right the ground other ends on you key common ground .. jeffrey.. ps still no log book oh hell.

**Comment by afarhan** [comment]
Jeff,
1. Can you confirm that the sbitx.db file is present in the data directory?
2. Type sqlite3 to check if it is installed properly.

If the two above fail, do this:

sudo apt update
sudo apt install sqlite3
sudo apt install libsqlite3-dev

cd data
sqlite3 sbitx.db < create_db.sql

**Comment by ok1rp** [comment]
Jeff

Did you put caps to paddle directly or into paddle jack inside Sbitx case please. 

73 - Petr, OK1RP
--
B: http://goo.gl/Fd2JhJ
YT: https://urlzs.com/UHNH9
MeWe: https://bit.ly/2HGPoDx
MeWe: https://bit.ly/2FmwvDt
--
機能するものを変更しないでください。
What could be easier..?  ¯‍∖‍_‍(‍ツ‍)‍_‍/‍¯

**Comment by m0prf** [comment]
hi i put them on the paddle key,but i do not see a problem putting them on the board if you can .. jeffrey

**Comment by m0prf** [comment]
still the bloody log book wont work, just says ABORT i got this radio to do ft8.. this must be must be sorted out by hf signals its not my job to mess with it for over 3 weeks,  still no damn logbook this rig should have not not gone to market it does not work
as intended its not for the buyer to fix it you would not by a car from show room and try to get it to work when you got home thats bloody barmy.  jeffrey
